import React, { Component } from 'react';
import {
  HeaderBar,
} from '../components';

const title = {
  pageTitle: 'My Recipe Store // Terms of Use and Privacy Policy',
};

export const siteHeaderStyle = {
  margin: '1em',
  fontSize: '2px',
  colour: 'orange',
};

class Terms extends Component {
  render() {
    return (
      <div className="Terms">
        <HeaderBar title={title} />
        <p></p>
        <div styles={siteHeaderStyle}>
          <p styles={siteHeaderStyle}>Terms of Service</p>
          <p>Your relationship with My Recipe Finder
Your use of My Recipe Finder’s products, software, services and web sites (referred to collectively as the “Services” in this document and excluding any services provided to you by My Recipe Finder under a separate written agreement) is subject to the terms of a legal agreement between you and My Recipe Finder. This document explains how the agreement is made up, and sets out some of the terms of that agreement.
Accepting the Terms
In order to use the Services, you must first agree to the Terms. You may not use the Services if you do not accept the Terms. You can accept the Terms by: clicking to accept or agree to the Terms, where this option is made available to you by My Recipe Finder in the user interface for any Service; or by actually using the Services. In this case, you understand and agree that My Recipe Finder will treat your use of the Services as acceptance of the Terms from that point onwards. You may not use the Services and may not accept the Terms if (a) you are not of legal age to form a binding contract with My Recipe Finder, or (b) you are a person barred from receiving the Services under the laws of the United States or other countries including the country in which you are resident or from which you use the Services.
Provision of the Services by My Recipe Finder
My Recipe Finder is constantly innovating in order to provide the best possible experience for its users. You acknowledge and agree that the form and nature of the Services which My Recipe Finder provides may change from time to time without prior notice to you. As part of this continuing innovation, you acknowledge and agree that My Recipe Finder may stop (permanently or temporarily) providing the Services (or any features within the Services) to you or to users generally at My Recipe Finder’s sole discretion, without prior notice to you. You may stop using the Services at any time. You do not need to specifically inform My Recipe Finder when you stop using the Services. You acknowledge and agree that if My Recipe Finder disables access to your account, you may be prevented from accessing the Services, your account details or any files or other content which is contained in your account. You acknowledge and agree that while My Recipe Finder may not currently have set a fixed upper limit on the number of transmissions you may send or receive through the Services or on the amount of storage space used for the provision of any Service, such fixed upper limits may be set by My Recipe Finder at any time, at My Recipe Finder’s discretion.
Use of the Services by you
In order to access certain Services, you may be required to provide information about yourself (such as identification or contact details) as part of the registration process for the Service, or as part of your continued use of the Services. You agree that any registration information you give to My Recipe Finder will always be accurate, correct and up to date. You agree to use the Services only for purposes that are permitted by (a) the Terms and (b) any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions (including any laws regarding the export of data or software to and from the United States or other relevant countries). You agree not to access (or attempt to access) any of the Services by any means other than through the interface that is provided by My Recipe Finder, unless you have been specifically allowed to do so in a separate agreement with My Recipe Finder. You specifically agree not to access (or attempt to access) any of the Services through any automated means (including use of scripts or web crawlers) and shall ensure that you comply with the instructions set out in any robots.txt file present on the Services. You agree that you will not engage in any activity that interferes with or disrupts the Services (or the servers and networks which are connected to the Services). Unless you have been specifically permitted to do so in a separate agreement with My Recipe Finder, you agree that you will not reproduce, duplicate, copy, sell, trade or resell the Services for any purpose. You agree that you are solely responsible for (and that My Recipe Finder has no responsibility to you or to any third party for) any breach of your obligations under the Terms and for the consequences (including any loss or damage which My Recipe Finder may suffer) of any such breach.
Your passwords and account security
You agree and understand that you are responsible for maintaining the confidentiality of passwords associated with any account you use to access the Services. Accordingly, you agree that you will be solely responsible to My Recipe Finder for all activities that occur under your account. If you become aware of any unauthorized use of your password or of your account, you agree to notify My Recipe Finder immediately.
Privacy and your personal information
For information about My Recipe Finder’s data protection practices, please read My Recipe Finder’s privacy policy. This policy explains how My Recipe Finder treats your personal information, and protects your privacy, when you use the Services. You agree to the use of your data in accordance with My Recipe Finder’s privacy policies.
Content in the Services
You understand that all information (such as data files, written text, computer software, music, audio files or other sounds, photographs, videos or other images) which you may have access to as part of, or through your use of, the Services are the sole responsibility of the person from which such content originated. All such information is referred to below as the “Content”. You should be aware that Content presented to you as part of the Services, including but not limited to advertisements in the Services and sponsored Content within the Services may be protected by intellectual property rights which are owned by the sponsors or advertisers who provide that Content to My Recipe Finder (or by other persons or companies on their behalf). You may not modify, rent, lease, loan, sell, distribute or create derivative works based on this Content (either in whole or in part) unless you have been specifically told that you may do so by My Recipe Finder or by the owners of that Content, in a separate agreement. My Recipe Finder reserves the right (but shall have no obligation) to pre-screen, review, flag, filter, modify, refuse or remove any or all Content from any Service.
Proprietary rights
You acknowledge and agree that My Recipe Finder (or My Recipe Finder’s licensors) own all legal right, title and interest in and to the Services, including any intellectual property rights which subsist in the Services (whether those rights happen to be registered or not, and wherever in the world those rights may exist). You further acknowledge that the Services may contain information which is designated confidential by My Recipe Finder and that you shall not disclose such information without My Recipe Finder’s prior written consent. Unless you have agreed otherwise in writing with My Recipe Finder, nothing in the Terms gives you a right to use any of My Recipe Finder’s trade names, trade marks, service marks, logos, domain names, and other distinctive brand features. If you have been given an explicit right to use any of these brand features in a separate written agreement with My Recipe Finder, then you agree that your use of such features shall be in compliance with that agreement, any applicable provisions of the Terms, and My Recipe Finder's brand feature use guidelines as updated from time to time. My Recipe Finder acknowledges and agrees that it obtains no right, title or interest from you (or your licensors) under these Terms in or to any Content that you submit, post, transmit or display on, or through, the Services, including any intellectual property rights which subsist in that Content (whether those rights happen to be registered or not, and wherever in the world those rights may exist). Unless you have agreed otherwise in writing with My Recipe Finder, you agree that you are responsible for protecting and enforcing those rights and that My Recipe Finder has no obligation to do so on your behalf. You agree that you shall not remove, obscure, or alter any proprietary rights notices (including copyright and trade mark notices) which may be affixed to or contained within the Services. Unless you have been expressly authorized to do so in writing by My Recipe Finder, you agree that in using the Services, you will not use any trade mark, service mark, trade name, logo of any company or organization in a way that is likely or intended to cause confusion about the owner or authorized user of such marks, names or logos.
License from My Recipe Finder
My Recipe Finder gives you a personal, worldwide, royalty-free, non-assignable and non-exclusive license to use the software provided to you by My Recipe Finder as part of the Services as provided to you by My Recipe Finder (referred to as the “Software” below). This license is for the sole purpose of enabling you to use and enjoy the benefit of the Services as provided by My Recipe Finder, in the manner permitted by the Terms. You may not (and you may not permit anyone else to) copy, modify, create a derivative work of, reverse engineer, decompile or otherwise attempt to extract the source code of the Software or any part thereof, unless this is expressly permitted or required by law, or unless you have been specifically told that you may do so by My Recipe Finder, in writing. Unless My Recipe Finder has given you specific written permission to do so, you may not assign (or grant a sub-license of) your rights to use the Software, grant a security interest in or over your rights to use the Software, or otherwise transfer any part of your rights to use the Software.
Content license from you
You retain copyright and any other rights you already hold in Content which you submit, post or display on or through, the Services. You understand that My Recipe Finder, in performing the required technical steps to provide the Services to our users, may (a) transmit or distribute your Content over various public networks and in various media; and (b) make such changes to your Content as are necessary to conform and adapt that Content to the technical requirements of connecting networks, devices, services or media. You agree that this license shall permit My Recipe Finder to take these actions. You confirm and warrant to My Recipe Finder that you have all the rights, power and authority necessary to grant the above license.
Software updates
The Software which you use may automatically download and install updates from time to time from My Recipe Finder. These updates are designed to improve, enhance and further develop the Services and may take the form of bug fixes, enhanced functions, new software modules and completely new versions. You agree to receive such updates (and permit My Recipe Finder to deliver these to you) as part of your use of the Services.
Ending your relationship with My Recipe Finder
The Terms will continue to apply until terminated by either you or My Recipe Finder as set out below. If you want to terminate your legal agreement with My Recipe Finder, you may do so by (a) notifying My Recipe Finder at any time and (b) closing your accounts for all of the Services which you use, where My Recipe Finder has made this option available to you. Your notice should be sent, in writing, to My Recipe Finder’s address which is set out at the beginning of these Terms. My Recipe Finder may at any time, terminate its legal agreement with you if:
(A) you have breached any provision of the Terms (or have acted in manner which clearly shows that you do not intend to, or are unable to comply with the provisions of the Terms); or
(B) My Recipe Finder is required to do so by law (for example, where the provision of the Services to you is, or becomes, unlawful); or
(C) the partner with whom My Recipe Finder offered the Services to you has terminated its relationship with My Recipe Finder or ceased to offer the Services to you; or
(D) My Recipe Finder is transitioning to no longer providing the Services to users in the country in which you are resident or from which you use the service; or
(E) the provision of the Services to you by My Recipe Finder is, in My Recipe Finder’s opinion, no longer commercially viable.
Nothing in this Section shall affect My Recipe Finder’s rights regarding provision of Services under Section 4 of the Terms. When these Terms come to an end, all of the legal rights, obligations and liabilities that you and My Recipe Finder have benefited from, been subject to (or which have accrued over time whilst the Terms have been in force) or which are expressed to continue indefinitely, shall be unaffected by this cessation, and the provisions of paragraph 20.7 shall continue to apply to such rights, obligations and liabilities indefinitely.
EXCLUSION OF WARRANTIES
NOTHING IN THESE TERMS, SHALL EXCLUDE OR LIMIT My Recipe Finder’S WARRANTY OR LIABILITY FOR LOSSES WHICH MAY NOT BE LAWFULLY EXCLUDED OR LIMITED BY APPLICABLE LAW. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR CONDITIONS OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR LOSS OR DAMAGE CAUSED BY NEGLIGENCE, BREACH OF CONTRACT OR BREACH OF IMPLIED TERMS, OR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, ONLY THE LIMITATIONS WHICH ARE LAWFUL IN YOUR JURISDICTION WILL APPLY TO YOU YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK AND THAT THE SERVICES ARE PROVIDED "AS IS" AND “AS AVAILABLE.” IN PARTICULAR, My Recipe Finder, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS DO NOT REPRESENT OR WARRANT TO YOU THAT:
(A) YOUR USE OF THE SERVICES WILL MEET YOUR REQUIREMENTS,
(B) YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR,
(C) ANY INFORMATION OBTAINED BY YOU AS A RESULT OF YOUR USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, AND
(D) THAT DEFECTS IN THE OPERATION OR FUNCTIONALITY OF ANY SOFTWARE PROVIDED TO YOU AS PART OF THE SERVICES WILL BE CORRECTED.
ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM My Recipe Finder OR THROUGH OR FROM THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS. My Recipe Finder FURTHER EXPRESSLY DISCLAIMS ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
LIMITATION OF LIABILITY
SUBJECT TO OVERALL PROVISION IN PARAGRAPH 14.1 ABOVE, YOU EXPRESSLY UNDERSTAND AND AGREE THAT My Recipe Finder, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS SHALL NOT BE LIABLE TO YOU FOR:
(A) ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL CONSEQUENTIAL OR EXEMPLARY DAMAGES WHICH MAY BE INCURRED BY YOU, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY.. THIS SHALL INCLUDE, BUT NOT BE LIMITED TO, ANY LOSS OF PROFIT (WHETHER INCURRED DIRECTLY OR INDIRECTLY), ANY LOSS OF GOODWILL OR BUSINESS REPUTATION, ANY LOSS OF DATA SUFFERED, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR OTHER INTANGIBLE LOSS;
(B) ANY LOSS OR DAMAGE WHICH MAY BE INCURRED BY YOU, INCLUDING BUT NOT LIMITED TO LOSS OR DAMAGE AS A RESULT OF:
(I) ANY RELIANCE PLACED BY YOU ON THE COMPLETENESS, ACCURACY OR EXISTENCE OF ANY ADVERTISING, OR AS A RESULT OF ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY ADVERTISER OR SPONSOR WHOSE ADVERTISING APPEARS ON THE SERVICES;
(II) ANY CHANGES WHICH My Recipe Finder MAY MAKE TO THE SERVICES, OR FOR ANY PERMANENT OR TEMPORARY CESSATION IN THE PROVISION OF THE SERVICES (OR ANY FEATURES WITHIN THE SERVICES);
(III) THE DELETION OF, CORRUPTION OF, OR FAILURE TO STORE, ANY CONTENT AND OTHER COMMUNICATIONS DATA MAINTAINED OR TRANSMITTED BY OR THROUGH YOUR USE OF THE SERVICES;
(III) YOUR FAILURE TO PROVIDE My Recipe Finder WITH ACCURATE ACCOUNT INFORMATION;
(IV) YOUR FAILURE TO KEEP YOUR PASSWORD OR ACCOUNT DETAILS SECURE AND CONFIDENTIAL;
THE LIMITATIONS ON My Recipe Finder’S LIABILITY TO YOU IN PARAGRAPH 15.1 ABOVE SHALL APPLY WHETHER OR NOT My Recipe Finder HAS BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING.
Copyright and trade mark policies
It is My Recipe Finder’s policy to respond to notices of alleged copyright infringement that comply with applicable international intellectual property law (including, in the United States, the Digital Millennium Copyright Act) and to terminating the accounts of repeat infringers.
Other content
The Services may include hyperlinks to other web sites or content or resources. My Recipe Finder may have no control over any web sites or resources which are provided by companies or persons other than My Recipe Finder. You acknowledge and agree that My Recipe Finder is not responsible for the availability of any such external sites or resources, and does not endorse any advertising, products or other materials on or available from such web sites or resources. You acknowledge and agree that My Recipe Finder is not liable for any loss or damage which may be incurred by you as a result of the availability of those external sites or resources, or as a result of any reliance placed by you on the completeness, accuracy or existence of any advertising, products or other materials on, or available from, such web sites or resources.
Changes to the Terms
My Recipe Finder may make changes to the Universal Terms or Additional Terms from time to time. When these changes are made, My Recipe Finder will make a new copy of the Universal Terms available and any new Additional Terms will be made available to you from within, or through, the affected Services. You understand and agree that if you use the Services after the date on which the Universal Terms or Additional Terms have changed, My Recipe Finder will treat your use as acceptance of the updated Universal Terms or Additional Terms.
General legal terms
Sometimes when you use the Services, you may (as a result of, or through your use of the Services) use a service or download a piece of software, or purchase goods, which are provided by another person or company. Your use of these other services, software or goods may be subject to separate terms between you and the company or person concerned. If so, the Terms do not affect your legal relationship with these other companies or individuals. The Terms constitute the whole legal agreement between you and My Recipe Finder and govern your use of the Services (but excluding any services which My Recipe Finder may provide to you under a separate written agreement), and completely replace any prior agreements between you and My Recipe Finder in relation to the Services. You agree that My Recipe Finder may provide you with notices, including those regarding changes to the Terms, by email, regular mail, or postings on the Services. You agree that if My Recipe Finder does not exercise or enforce any legal right or remedy which is contained in the Terms (or which My Recipe Finder has the benefit of under any applicable law), this will not be taken to be a formal waiver of My Recipe Finder’s rights and that those rights or remedies will still be available to My Recipe Finder. If any court of law, having the jurisdiction to decide on this matter, rules that any provision of these Terms is invalid, then that provision will be removed from the Terms without affecting the rest of the Terms. The remaining provisions of the Terms will continue to be valid and enforceable. You acknowledge and agree that each member of the group of companies of which My Recipe Finder is the parent shall be third party beneficiaries to the Terms and that such other companies shall be entitled to directly enforce, and rely upon, any provision of the Terms which confers a benefit on (or rights in favor of) them. Other than this, no other person or company shall be third party beneficiaries to the Terms. The Terms, and your relationship with My Recipe Finder under the Terms, shall be governed by the laws of the State of New York without regard to its conflict of laws provisions. You and My Recipe Finder agree to submit to the exclusive jurisdiction of the courts located within England, United Kingdom to resolve any legal matter arising from the Terms. Notwithstanding this, you agree that My Recipe Finder shall still be allowed to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction.</p>
          <p styles={siteHeaderStyle}>Privacy Policy</p>
          <p>Last Updated: 6th Feb 2019</p>

<p>My Recipe Finder.com Web Site Privacy Policy
This Privacy Policy governs your use of the websites published and maintained by My Recipe Finder, including My Recipe Finder.com. By visiting this website, and/or using the services offered on or through this website, you agree to the terms of this Privacy Policy as they may be amended from time to time. As we update and expand our website, this Privacy Policy may change, so check back to this page from time to time. This Privacy Policy is incorporated into, and part of, the My Recipe Finder Terms and Conditions, which governs your use of this website in general.

Summary
It is My Recipe Finder’s policy to respect and protect the privacy of visitors to this website and associated services. Accordingly, My Recipe Finder DOES NOT extract, without permission, Personal Information (as defined below) about its visitors or their computer at any time while on My Recipe Finder’s website, except for Personal Information that is actively provided by such visitors through registration, logging in and out, online forms or other means. My Recipe Finder will, however, analyze information about our visitors as a group to make our website and apps better, but visitors are not individually identified when we do this.

When dealing with children who we have knowledge are under the age of 13, My Recipe Finder follows stringent guidelines that prohibit the sharing of Personal Information with any third parties, except in limited circumstances such as our service providers who use such information on our behalf. Our privacy policies regarding children are outlined in My Recipe Finder’s Parental Consent Policy section below.

This Privacy Policy does not apply to information that you may provide to us, or that we may obtain, other than through our website, such as by phone, through postal mail and through other live and print media.

This website is intended for users who are located in the United States of America. This Privacy Policy shall be interpreted under the laws of the United States, regardless of the location of individual users.

What We Collect
My Recipe Finder may collect a variety of statistical data about its website visitors. This data includes the source IP address of the visitor, the time of visit, the areas of the site visited and information about browser, operating system and other system parameters. As of the date of this Privacy Policy, none of this information is used to personally identify any individual visitor, and is used solely for the purposes of analyzing overall traffic and usage patterns. However, My Recipe Finder reserves the right to begin matching such usage data with an individual’s Personal Information subsequent to the date of this Privacy Policy.

In order to make your visits to our website and use of the services available on or through our website as worthwhile as possible, My Recipe Finder may also collect Personal Information about its visitors, but only when a visitor provides such Personal Information to us in the process of ordering subscriptions, entering contests or sweepstakes, signing up for our newsletter(s), using our "Feedback" feature, registering with the website or using other services available on or through our Website. The information that you give us and information about your order, purchases or other activities on the website may be combined with other Personal Information (such as demographic information and past purchase history) available from our records and other sources. "Personal Information" includes, for example, names, postal addresses, email addresses, wireless addresses, age, credit card and other payment information, demographic information, purchase history, subscription information and/or other information that may identify you as an individual or allow online or offline contact with you as an individual. This information is used by My Recipe Finder to fulfill your requests and for marketing and research purposes. This information may also be shared with other marketers to bring you offers of interest. If you prefer that we do not share your name and address with other marketers, please see the "Right to Opt Out" section below. Certain areas of My Recipe Finder’s Website will require user registration in order to gain access; once you register with the My Recipe Finder website to use that content, you will no longer be anonymous to us.

Use of Cookies and Other Tracking Technologies
My Recipe Finder may use "cookie" technology to enhance a visitor's online experience by making it easier to navigate through our Website or to make an activity work better.

Cookies are small pieces of information or data files that are sent through your browser or related software from a Web server and are stored on your computer’s hard drive. Cookies may be used to track where you travel on our website and what you look at and purchase, and they allow a computer to "remember" information from our Website for future use. The use of cookies is an industry standard and is practiced by most major websites. Cookies alone tell us nothing about who you are, but they may enable us to relate your use of our website to other information, including your Personal Information, which you have provided to us when you registered or performed other activities while visiting our website. All of these purposes serve to enhance your experience while using our services in the ways described below.

Most Web browsers can be set to inform you when a cookie has been sent to you and provide you with the opportunity to refuse that cookie. Additionally, if you have a Flash player installed on your computer, your Flash player can be set to reject or delete Flash cookies. However, refusing a cookie may, in some cases, preclude you from using, or negatively impact the display or function of, the website or certain areas or features of the website.

We may use cookies and other tracking technologies in a variety of ways, including:

Keeping count of return visits to our website or our advertisers’ or partners’ sites
Accumulating and reporting anonymous, aggregate (data collected in mass), statistical information on website and advertisement usage
Determining which features our customers like best
Saving your password so you don’t have to re-enter it each time you visit our Web Site
How My Recipe Finder Uses Personal Information
Personal Information is used to enhance and custom-tailor each user's experience on the website. Such information may be used to determine what site content is of interest to which users, what types of email newsletters and other communications are appropriate for individual users, and to identify user-generated content such as message board postings, votes in online polls and participation in online games. Such information will also be used, for example, to process your orders, respond to your requests and inquiries and provide you with the services and features offered on or through our Website.

Right to Opt-Out
At any time, you may opt-out of receiving notifications and other messages from My Recipe Finder by going to the profile tab on My Recipe Finder.com (https://www.My Recipe Finder.com/profile.aspx) and deselect the “Receive My Recipe Finder News” option. This option is deselected by default.

You can also choose to disable or selectively turn off cookies or third-party cookies in your web browser settings. It is important to note that different devices (i.e. mobile, tablet and desktop) use different identifiers and different technologies, so that you must opt out separately from each web browser and each device that you would like to be opted out. If you opt-out of targeted advertising, we will no longer collect User Information described within this policy.

My Recipe Finder may also use Personal Information to maintain our internal record keeping. We reserve the right to match information collected from you through different means or at different times, including both Personal Information and website usage information, and use such information along with information obtained from other sources. In addition, we may send you notices (for example, in the form of e-mails, mailings, and the like), and otherwise correspond with you, about products, services, companies and events, sponsored by us and others, that we think might interest you. You may opt-out of receiving such notices from us by following the instructions in the Right to Opt Out section above.

In addition, My Recipe Finder may use Personal Information to generate aggregate data about our website’s visitors.

Send-to-a-Friend
Visitors to the website can forward information about areas and/or services available on or through the website, to their friends. In order to do this, visitors are asked to provide only their first name and their friend's first name and e-mail address, all of which are deleted once the postcard is sent.

Requests For Feedback
My Recipe Finder may request feedback from visitors to the website regarding an activity or piece of content on the website. Such feedback is used for internal purposes only.

Correspondence and Newsletters
My Recipe Finder uses automated email systems to e-mail newsletters and to collect and answer correspondence from our visitors. My Recipe Finder tries to make it easy for visitors to contact us and we provide easy instructions on our website on how you can either edit Personal Information previously given (such as your address) or opt out of receiving any automated messages generated by My Recipe Finder. For more information on opting out, please see the Right to Opt Out section above. Should you have a technical problem doing this please contact support@My Recipe Finder.com.

Public Forums
When you contribute to a public area or feature of our website, such as a chat room, bulletin board, list serve, blog, wiki or other open forum that we may make available on or through our website, the information that you submit will be made available to the general public. For this reason, we recommend that you do not submit any sensitive information, including your full name, home address, phone number, other information that would enable other users to locate you, or financial information on these areas of our website. Instead, you should make up a username that does not disclose your personal identity.

Business Transfer
In the event that My Recipe Finder, or substantially all of its assets, are acquired by one or more third parties as a result of an acquisition, merger, sale, reorganization, consolidation or liquidation, Personal Information may be one of the transferred assets.

Third Party Ad Servers
My Recipe Finder uses GourmetAds, a third party advertising provider, to serve advertisements on the My Recipe Finder.com website. This companies may use information about your visits to this and other Websites in order to provide advertisements about goods and services of interest to you. These companies may employ cookies and clear gifs to measure advertising effectiveness. Any information that these third parties collect via cookies and clear gifs is generally not personally identifiable (unless, for example, you provide personally identifiable information to them through an ad or email message). We encourage you to read these businesses' privacy policies if you should have any concerns about how they will care for your Personal Information.

Advertisers and Third Party "Linked-To" Web Sites
My Recipe Finder may include advertisements and/or links to websites operated by third parties that are not sponsors and are not affiliated with My Recipe Finder. My Recipe Finder tries to make sure that when there are links away from the website, they are working and lead visitors to interesting, fun and informative areas. However, it is hard to guarantee what exactly is presented on other websites or where links elsewhere may lead. My Recipe Finder is not responsible for the content, practices, or information provided or requested on websites operated by third parties. Further, advertisements on and links to or from My Recipe Finder.com do not constitute sponsorship, endorsement, or approval by My Recipe Finder of the content, policies, practices or products or services offered on these websites.

Parents/guardians should check each website's privacy policy and terms of use in order to understand their policies and practices regarding the collection and use of personally identifiable information. My Recipe Finder also suggests that parents/guardians review the privacy policies of all websites that their children visit, including those websites linking to or from the My Recipe Finder website. Information provided to those websites will be subject to the privacy policy posted at that website.

Security
The importance of security for all Personal Information associated with visitors to our website is of utmost concern to us. My Recipe Finder exercises great care and implements a variety of technologies in an effort to help make the My Recipe Finder website secure against unauthorized access and to protect the Personal Information visitors choose to provide to us. My Recipe Finder periodically reviews and updates these measures. Unfortunately, due to the inherent nature of the Internet as an open global communications vehicle, no data transmission over the Internet can be guaranteed to be secure, and My Recipe Finder cannot guarantee that information, during transmission through the Internet or while stored on our system or otherwise in our care, will be absolutely safe from intrusion by others, such as hackers. As a result, while My Recipe Finder strives to protect a visitor's Personal Information, My Recipe Finder cannot ensure or warrant the security of any information transmitted to us or from our online products or services, and a visitor does so at his/her own risk. My Recipe Finder uses the industry standard, SSL (secure socket layer) encryption when credit card information is transmitted to us.

If you contact us by email or a "contact us" or similar feature on our website, you should be aware that your transmission might not be secure. A third party could view information you send by these methods in transit.

You may be able to create an account on our website with a username and password. If so, you are responsible for maintaining the strict confidentiality of your account password, and you shall be responsible for any access to or use of the website by you or any person or entity using your password, whether or not such access or use has been authorized by or on behalf of you, and whether or not such person or entity is your employee or agent. You agree to (a) immediately notify My Recipe Finder of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. It is your sole responsibility to control the dissemination and use of your password, control access to and use of your account, and notify My Recipe Finder when you desire to cancel your account on this website. We will not be responsible or liable for any loss or damage arising from your failure to comply with this provision.

We will have no liability for disclosure of your information due to errors or unauthorized acts of third parties during or after transmission.

In the unlikely event that we believe that the security of your Personal Information in our possession or control may have been compromised, we may seek to notify you of that development. If a notification is appropriate, we would endeavor to do so as promptly as possible under the circumstances, and, to the extent we have your email address, we may notify you by email. You consent to our use of e-mail as a means of such notification. If you prefer for us to use another method to notify you in this situation, please email us at support@My Recipe Finder.com with the alternative contact information you wish to be used.

Phishing
With identity theft a continuing problem, it has become increasingly common for unauthorized individuals to send e-mail messages to consumers, purporting to represent a legitimate company such as a bank or online merchant, requesting that the consumer provide personal, often sensitive information. Sometimes, the domain name of the e-mail address from which the email appears to have been sent, and the domain name of the website requesting such information, appears to be the domain name of a legitimate, trusted company. In reality, such sensitive information is received by an unauthorized individual to be used for purposes of identity theft. This illegal activity has come to be known as "phishing."

If you receive an e-mail or other correspondence requesting that you provide any sensitive information (including your website password or credit card information) via e-mail or to a Website that does not seem to be affiliated with our website, or that otherwise seems suspicious to you, please do not provide such information, and report such request to us at support@My Recipe Finder.com.

Consent to Processing
By providing Personal Information to this website, you understand and consent to the collection, maintenance, processing and transfer of such information in and to the United States and other countries and territories.

Changes to this Privacy Policy
My Recipe Finder reserves the right to change or update this Privacy Policy, or any other of our policies or practices, at any time, and will notify users of this website by posting such changed or updated Privacy Policy on this page. Any changes or updates will be effective immediately upon posting to this website. Under certain circumstances, we may also elect to notify you of changes or updates to our Privacy Policy by additional means, such as posting a notice on the front page of our website to sending you an email.</p>
        </div>
      </div>
    );
  }
}

export default Terms;
